extends Node

enum Targets {FRIENDLY, HOSTILE, RANDOM}
enum Enhancements {STRENGTH_UP, STRENGTH_DOWN, DEFENSE_UP, DEFENSE_DOWN, SPEED_UP, 
	SPEED_DOWN, SIZE_UP, SIZE_DOWN, JUMP_UP, JUMP_DOWN, POISON, ACID, SLOW, BLIND, 
	SILENCE, CHARM, CONFUSION, LIFESTEAL, DAMAGE_OVER_TIME, RANDOM}
enum DamageTypes {NORMAL, FIRE, WATER, ICE, ELECTRICITY, EARTH, WIND, DARK, LIGHT, 
	ANTI, ULTIMA, HEAL, SHIELD, RANDOM}
enum AoeTypes {SQUARE, CIRCLE, TRIANGLE, PENTAGON, CONE, CRESCENT, SINGLES, RANDOM}
enum Directions {FRONT, DOWN_FRONT, DOWN, DOWN_BACK, BACK, UP_BACK, UP, UP_FRONT,
	RANDOM}
enum Effects {CIRCLING, HOMING, BOUNCING, REFLECTING, PIERCING, STICKY, RETURNING, 
	EXPLOSIVE, TRAP, EXPANDING, SHRINKING, SPRAYING, RANDOM}
